PRODUCT_PACKAGES += \
   mcDriverDaemon \
   FlipFlap \
   libtfa98xx \
   audio_amplifier.universal7870 \
   libtinycompress \
   fingerprint.exynos5 \
   libbauthtzcommon_shim \
   android.hardware.biometrics.fingerprint@2.1-impl \
   android.hardware.biometrics.fingerprint@2.1-service \
   lights.universal7870 \
   android.hardware.light@2.0-impl \
   AdvancedDisplay \
   android.hardware.nfc@1.0-impl \
   libnfc-nci \
   libnfc_nci_jni \
   com.android.nfc_extras \
   NfcNci \
   Tag \
   android.hardware.wifi@1.0 \
   android.hardware.wifi@1.0-impl \
   android.hardware.wifi@1.0-service \
   hostapd \
   libqsap_sdk \
   libQWiFiSoftApCfg \
   libwpa_client \
   wificond \
   wifilogd \
   wifiloader \
   wlutil \
   wpa_supplicant \
   wpa_supplicant.conf
